-- BOARD 테이블 생성 SQL문

  CREATE TABLE "TEAM3"."BOARD" 
   (	"NO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"REG_DATE" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPD_DATE" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "BOARD_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM3"."BOARD"."NO" IS '글번호';
   COMMENT ON COLUMN "TEAM3"."BOARD"."WRITER" IS '글쓴이';
   COMMENT ON COLUMN "TEAM3"."BOARD"."TITLE" IS '글제목';
   COMMENT ON COLUMN "TEAM3"."BOARD"."CONTENT" IS '내용';
   COMMENT ON COLUMN "TEAM3"."BOARD"."REG_DATE" IS '등록일자';
   COMMENT ON COLUMN "TEAM3"."BOARD"."UPD_DATE" IS '수정일자';

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TEAM3"."BOARD_TRG" 
BEFORE INSERT ON BOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NO IS NULL THEN
      SELECT SEQ_BOARD_NO.NEXTVAL INTO :NEW.NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEAM3"."BOARD_TRG" ENABLE;


--  BOARD 테이블 샘플 데이터
INSERT INTO BOARD (NO, TITLE, WRITER, CONTENT)
VALUES(SEQ_BOARD_NO.NEXTVAL, '행운의 편지', '김조은', '이 편지는...');

INSERT INTO BOARD (NO, TITLE, WRITER, CONTENT)
VALUES(SEQ_BOARD_NO.NEXTVAL, '누르면 당첨확률 100', '뉴진스', '꽝~');


